<?php
/**
 * @file
 * hp_localization.features.translations.inc
 */

/**
 * Implements hook_translations_defaults().
 */
function hp_localization_translations_defaults() {
  $translations = array();
  $translations['de:menu']['25b3054f6d896460cf34ded6737a144c'] = array(
    'source' => 'Resources',
    'context' => 'item:1897:title',
    'location' => 'menu:item:1897:title',
    'translation' => 'Ressourcen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['27e270668c02466b491b4385eee985fb'] = array(
    'source' => 'Products',
    'context' => 'item:1895:title',
    'location' => 'menu:item:1895:title',
    'translation' => 'Produkte',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['46809cd9b42eebbefa790af56a89931a'] = array(
    'source' => 'Products',
    'context' => 'item:1894:title',
    'location' => 'menu:item:1894:title',
    'translation' => 'Produkte',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['4c3349f4c4a67918451abef2c889d2c4'] = array(
    'source' => 'Company',
    'context' => 'item:1899:title',
    'location' => 'menu:item:1899:title',
    'translation' => 'Unternehmen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['554975b66754baf035eabf6c464aec1a'] = array(
    'source' => 'Get Help',
    'context' => 'item:1921:title',
    'location' => 'menu:item:1921:title',
    'translation' => 'Holen Sie sich Hilfe',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['641fdb8d5ef275ff65b5c2de0570d5a0'] = array(
    'source' => 'Privacy Statement',
    'context' => 'item:1919:title',
    'location' => 'menu:item:1919:title',
    'translation' => 'Datenschutzerklärung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['774f241cd0980762e52bfdd0f2da07b1'] = array(
    'source' => 'Resources',
    'context' => 'item:1920:title',
    'location' => 'menu:item:1920:title',
    'translation' => 'Ressourcen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['7dc3e7be42ad1128ea47db5b633e2262'] = array(
    'source' => 'Products',
    'context' => 'item:1894:description',
    'location' => 'menu:item:1894:description',
    'translation' => 'Produkte',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['7f6806acbb3d7bf1d22e4f2dcfef9bc0'] = array(
    'source' => 'Community',
    'context' => 'item:1896:title',
    'location' => 'menu:item:1896:title',
    'translation' => 'Gemeinde',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['87d06325551bfa9a7e24196ad1ee20c7'] = array(
    'source' => 'Terms of Use',
    'context' => 'item:2070:title',
    'location' => 'menu:item:2070:title',
    'translation' => 'Nutzungsbedingungen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['8971d1cb788c9d4d55ad1f630d8951b2'] = array(
    'source' => '/buy/app-pulse',
    'context' => 'item:2070:description',
    'location' => 'menu:item:2070:description',
    'translation' => '/buy/app-pulse',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['9089a76b619ba393825f1e58c3b28478'] = array(
    'source' => 'Community',
    'context' => 'item:1898:title',
    'location' => 'menu:item:1898:title',
    'translation' => 'Gemeinde',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['917fff35fc7de6abf51cec9e57065ee1'] = array(
    'source' => 'Forums',
    'context' => 'item:1929:title',
    'location' => 'menu:item:1929:title',
    'translation' => 'Foren',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['a12ca5d37a47216ba187856d2085a660'] = array(
    'source' => 'Forums',
    'context' => 'item:1922:title',
    'location' => 'menu:item:1922:title',
    'translation' => 'Foren',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['f13a091538f25b2c4ebfbf3d7c35f4ec'] = array(
    'source' => 'Community',
    'context' => 'item:1896:description',
    'location' => 'menu:item:1896:description',
    'translation' => 'Gemeinde',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['f1b07a71e5c795c2da8304d9cc766aaa'] = array(
    'source' => 'Events',
    'context' => 'item:1924:title',
    'location' => 'menu:item:1924:title',
    'translation' => 'Geschehen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['feb558f93f4b69cb3964c13927447f43'] = array(
    'source' => 'Events',
    'context' => 'item:1930:title',
    'location' => 'menu:item:1930:title',
    'translation' => 'Geschehen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['25b3054f6d896460cf34ded6737a144c'] = array(
    'source' => 'Resources',
    'context' => 'item:1897:title',
    'location' => 'menu:item:1897:title',
    'translation' => 'Recursos',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['27e270668c02466b491b4385eee985fb'] = array(
    'source' => 'Products',
    'context' => 'item:1895:title',
    'location' => 'menu:item:1895:title',
    'translation' => 'Productos',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['46809cd9b42eebbefa790af56a89931a'] = array(
    'source' => 'Products',
    'context' => 'item:1894:title',
    'location' => 'menu:item:1894:title',
    'translation' => 'Productos',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['4c3349f4c4a67918451abef2c889d2c4'] = array(
    'source' => 'Company',
    'context' => 'item:1899:title',
    'location' => 'menu:item:1899:title',
    'translation' => 'empresa',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['554975b66754baf035eabf6c464aec1a'] = array(
    'source' => 'Get Help',
    'context' => 'item:1921:title',
    'location' => 'menu:item:1921:title',
    'translation' => 'Obtener Ayuda',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['641fdb8d5ef275ff65b5c2de0570d5a0'] = array(
    'source' => 'Privacy Statement',
    'context' => 'item:1919:title',
    'location' => 'menu:item:1919:title',
    'translation' => 'Declaración de Privacidad',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['774f241cd0980762e52bfdd0f2da07b1'] = array(
    'source' => 'Resources',
    'context' => 'item:1920:title',
    'location' => 'menu:item:1920:title',
    'translation' => 'Recursos',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['7dc3e7be42ad1128ea47db5b633e2262'] = array(
    'source' => 'Products',
    'context' => 'item:1894:description',
    'location' => 'menu:item:1894:description',
    'translation' => 'Productos',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['7f6806acbb3d7bf1d22e4f2dcfef9bc0'] = array(
    'source' => 'Community',
    'context' => 'item:1896:title',
    'location' => 'menu:item:1896:title',
    'translation' => 'comunidad',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['87d06325551bfa9a7e24196ad1ee20c7'] = array(
    'source' => 'Terms of Use',
    'context' => 'item:2070:title',
    'location' => 'menu:item:2070:title',
    'translation' => 'Condiciones de uso',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['8971d1cb788c9d4d55ad1f630d8951b2'] = array(
    'source' => '/buy/app-pulse',
    'context' => 'item:2070:description',
    'location' => 'menu:item:2070:description',
    'translation' => '/buy/app-pulse',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['9089a76b619ba393825f1e58c3b28478'] = array(
    'source' => 'Community',
    'context' => 'item:1898:title',
    'location' => 'menu:item:1898:title',
    'translation' => 'comunidad',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['917fff35fc7de6abf51cec9e57065ee1'] = array(
    'source' => 'Forums',
    'context' => 'item:1929:title',
    'location' => 'menu:item:1929:title',
    'translation' => 'Foros',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['9f2933de65b8814c6b6b0e2a7330f3b3'] = array(
    'source' => 'Jobs',
    'context' => 'item:1918:title',
    'location' => 'menu:item:1918:title',
    'translation' => 'Empleos',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['a12ca5d37a47216ba187856d2085a660'] = array(
    'source' => 'Forums',
    'context' => 'item:1922:title',
    'location' => 'menu:item:1922:title',
    'translation' => 'Foros',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['f13a091538f25b2c4ebfbf3d7c35f4ec'] = array(
    'source' => 'Community',
    'context' => 'item:1896:description',
    'location' => 'menu:item:1896:description',
    'translation' => 'comunidad',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['f1b07a71e5c795c2da8304d9cc766aaa'] = array(
    'source' => 'Events',
    'context' => 'item:1924:title',
    'location' => 'menu:item:1924:title',
    'translation' => 'Eventos',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['es:menu']['feb558f93f4b69cb3964c13927447f43'] = array(
    'source' => 'Events',
    'context' => 'item:1930:title',
    'location' => 'menu:item:1930:title',
    'translation' => 'Eventos',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['25b3054f6d896460cf34ded6737a144c'] = array(
    'source' => 'Resources',
    'context' => 'item:1897:title',
    'location' => 'menu:item:1897:title',
    'translation' => 'ressources',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['27e270668c02466b491b4385eee985fb'] = array(
    'source' => 'Products',
    'context' => 'item:1895:title',
    'location' => 'menu:item:1895:title',
    'translation' => 'produits',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['46809cd9b42eebbefa790af56a89931a'] = array(
    'source' => 'Products',
    'context' => 'item:1894:title',
    'location' => 'menu:item:1894:title',
    'translation' => 'produits',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['4c3349f4c4a67918451abef2c889d2c4'] = array(
    'source' => 'Company',
    'context' => 'item:1899:title',
    'location' => 'menu:item:1899:title',
    'translation' => 'société',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['554975b66754baf035eabf6c464aec1a'] = array(
    'source' => 'Get Help',
    'context' => 'item:1921:title',
    'location' => 'menu:item:1921:title',
    'translation' => 'Aide',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['641fdb8d5ef275ff65b5c2de0570d5a0'] = array(
    'source' => 'Privacy Statement',
    'context' => 'item:1919:title',
    'location' => 'menu:item:1919:title',
    'translation' => 'Déclaration de confidentialité',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['774f241cd0980762e52bfdd0f2da07b1'] = array(
    'source' => 'Resources',
    'context' => 'item:1920:title',
    'location' => 'menu:item:1920:title',
    'translation' => 'ressources',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['7dc3e7be42ad1128ea47db5b633e2262'] = array(
    'source' => 'Products',
    'context' => 'item:1894:description',
    'location' => 'menu:item:1894:description',
    'translation' => 'produits',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['7f6806acbb3d7bf1d22e4f2dcfef9bc0'] = array(
    'source' => 'Community',
    'context' => 'item:1896:title',
    'location' => 'menu:item:1896:title',
    'translation' => 'communauté',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['87d06325551bfa9a7e24196ad1ee20c7'] = array(
    'source' => 'Terms of Use',
    'context' => 'item:2070:title',
    'location' => 'menu:item:2070:title',
    'translation' => 'Conditions d\'utilisation',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['8971d1cb788c9d4d55ad1f630d8951b2'] = array(
    'source' => '/buy/app-pulse',
    'context' => 'item:2070:description',
    'location' => 'menu:item:2070:description',
    'translation' => '/buy/app-pulse',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['9089a76b619ba393825f1e58c3b28478'] = array(
    'source' => 'Community',
    'context' => 'item:1898:title',
    'location' => 'menu:item:1898:title',
    'translation' => 'communauté',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['9f2933de65b8814c6b6b0e2a7330f3b3'] = array(
    'source' => 'Jobs',
    'context' => 'item:1918:title',
    'location' => 'menu:item:1918:title',
    'translation' => 'Offres d\'emploi',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['f13a091538f25b2c4ebfbf3d7c35f4ec'] = array(
    'source' => 'Community',
    'context' => 'item:1896:description',
    'location' => 'menu:item:1896:description',
    'translation' => 'communauté',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['f1b07a71e5c795c2da8304d9cc766aaa'] = array(
    'source' => 'Events',
    'context' => 'item:1924:title',
    'location' => 'menu:item:1924:title',
    'translation' => 'événements',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['fr:menu']['feb558f93f4b69cb3964c13927447f43'] = array(
    'source' => 'Events',
    'context' => 'item:1930:title',
    'location' => 'menu:item:1930:title',
    'translation' => 'événements',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['25b3054f6d896460cf34ded6737a144c'] = array(
    'source' => 'Resources',
    'context' => 'item:1897:title',
    'location' => 'menu:item:1897:title',
    'translation' => 'risorse',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['27e270668c02466b491b4385eee985fb'] = array(
    'source' => 'Products',
    'context' => 'item:1895:title',
    'location' => 'menu:item:1895:title',
    'translation' => 'prodotti',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['46809cd9b42eebbefa790af56a89931a'] = array(
    'source' => 'Products',
    'context' => 'item:1894:title',
    'location' => 'menu:item:1894:title',
    'translation' => 'prodotti',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['4c3349f4c4a67918451abef2c889d2c4'] = array(
    'source' => 'Company',
    'context' => 'item:1899:title',
    'location' => 'menu:item:1899:title',
    'translation' => 'società',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['554975b66754baf035eabf6c464aec1a'] = array(
    'source' => 'Get Help',
    'context' => 'item:1921:title',
    'location' => 'menu:item:1921:title',
    'translation' => 'ottenere aiuto',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['641fdb8d5ef275ff65b5c2de0570d5a0'] = array(
    'source' => 'Privacy Statement',
    'context' => 'item:1919:title',
    'location' => 'menu:item:1919:title',
    'translation' => 'Dichiarazione per la Privacy',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['774f241cd0980762e52bfdd0f2da07b1'] = array(
    'source' => 'Resources',
    'context' => 'item:1920:title',
    'location' => 'menu:item:1920:title',
    'translation' => 'risorse',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['7dc3e7be42ad1128ea47db5b633e2262'] = array(
    'source' => 'Products',
    'context' => 'item:1894:description',
    'location' => 'menu:item:1894:description',
    'translation' => 'prodotti',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['7f6806acbb3d7bf1d22e4f2dcfef9bc0'] = array(
    'source' => 'Community',
    'context' => 'item:1896:title',
    'location' => 'menu:item:1896:title',
    'translation' => 'comunità',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['87d06325551bfa9a7e24196ad1ee20c7'] = array(
    'source' => 'Terms of Use',
    'context' => 'item:2070:title',
    'location' => 'menu:item:2070:title',
    'translation' => 'Termini di utilizzo',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['8971d1cb788c9d4d55ad1f630d8951b2'] = array(
    'source' => '/buy/app-pulse',
    'context' => 'item:2070:description',
    'location' => 'menu:item:2070:description',
    'translation' => '/buy/app-pulse',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['9089a76b619ba393825f1e58c3b28478'] = array(
    'source' => 'Community',
    'context' => 'item:1898:title',
    'location' => 'menu:item:1898:title',
    'translation' => 'comunità',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['9f2933de65b8814c6b6b0e2a7330f3b3'] = array(
    'source' => 'Jobs',
    'context' => 'item:1918:title',
    'location' => 'menu:item:1918:title',
    'translation' => 'Offerte di lavoro',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['a12ca5d37a47216ba187856d2085a660'] = array(
    'source' => 'Forums',
    'context' => 'item:1922:title',
    'location' => 'menu:item:1922:title',
    'translation' => 'Forum',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['f13a091538f25b2c4ebfbf3d7c35f4ec'] = array(
    'source' => 'Community',
    'context' => 'item:1896:description',
    'location' => 'menu:item:1896:description',
    'translation' => 'comunità',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['f1b07a71e5c795c2da8304d9cc766aaa'] = array(
    'source' => 'Events',
    'context' => 'item:1924:title',
    'location' => 'menu:item:1924:title',
    'translation' => 'eventi',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['it:menu']['feb558f93f4b69cb3964c13927447f43'] = array(
    'source' => 'Events',
    'context' => 'item:1930:title',
    'location' => 'menu:item:1930:title',
    'translation' => 'eventi',
    'plid' => 0,
    'plural' => 0,
  );
  return $translations;
}
